"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Coisa_1 = require("./Coisa");
const CurtoAlcance_1 = require("./CurtoAlcance");
const Guilda_1 = require("./Guilda");
const LongoAlcance_1 = require("./LongoAlcance");
let LegiaoDoMal = new Guilda_1.Guildas("Legião do Mal");
let Robin = new CurtoAlcance_1.CurtoAlcance("Robin");
let Coringa = new LongoAlcance_1.LongoAlcance("Coringa");
let Arlequina = new CurtoAlcance_1.CurtoAlcance("Arlequina");
let livro = new Coisa_1.Coisa(1000, "o mundo de sofia");
LegiaoDoMal.addMembro(Coringa);
LegiaoDoMal.addMembro(Arlequina);
Coringa.addLevel(1);
Robin.addLevel(1);
LegiaoDoMal.removeMembro(Coringa);
console.log("Inicial", Robin.getNome(), Robin.getVida());
console.log("Inicial", Coringa.getNome(), Coringa.getVida());
Robin.machucar(500, Coringa, 2);
console.log("Primeiro ataque", Robin.getNome(), Robin.getVida());
console.log("Primeiro Ataque", Coringa.getNome(), Coringa.getVida());
Coringa.curar(Coringa, 2000);
console.log("Curou", Coringa.getNome(), Coringa.getVida());
Robin.machucar(100, Coringa, 10);
console.log("Segundo Ataque", Coringa.getNome(), Coringa.getVida());
Arlequina.curar(Coringa, 200);
console.log("Curou", Arlequina.getNome(), Arlequina.getVida());
Robin.machucar(50, Coringa, 5);
console.log("Terceiro Ataque", Coringa.getNome(), Coringa.getVida());
console.log(Coringa.getGuilda());
Coringa.machucar(500, livro, 5);
console.log(livro.getVida());
//# sourceMappingURL=app.js.map